### PR TITLE
Update check-update to 0.0.8

### PR DESCRIPTION
**Pull request by cedced19**
The new version allow to don't send useless options in some case.

### CODE REVIEW

**Comment by Nedomas** [comment]
Thanks, Cédric. We'll put it into the next release! :heart:

**Comment by cedced19** [comment]
Ok, at the beginning I created check-update for my software, but when I saw that you use my software, I saw that it was not the best way to do that. And so I made a new version.
You're welcome! :heart:

**Comment by Nedomas** [comment]
I really like this updater - its simple and has good API. Thanks for bringing it to the community! :+1: 

I've merged it in @ https://github.com/closeheat/cli/commit/6b93040b8a7299a4c8ccd01bc718b0357af2b972

**Comment by cedced19** [comment]
I think that I can close and delete my fork then.

**Comment by Nedomas** [comment]
I've checked it out and it works great! It is live with 0.19.3. 

Thanks again, Cédric.

**Pull request closed without merging**
